### ISSUE TITLE
Vite doesn't refresh the frontend content

### ISSUE THREAD

**Issue by igor-devx** [SaeedYasin/shopify-app-template-node#11]
Hi @SaeedYasin 
Vite doesn't refresh the content when you change smth in the frontend code. There is a need to manually rebuild the source code to see the changes. Do you know, why it is happening? Do you have the same issue? I already updated vite.config.js , but it didn't help to solve this issue.
 server: {
    watch: {
      usePolling: true,
    },
   }

**Comment by SaeedYasin** [comment]
In my testing, it works. The only caveat is that it is delayed. It can take some time to update.
