### ISSUE TITLE
Build from `Dockerfile` crashes

### ISSUE THREAD

**Issue by afunnydev** [SaeedYasin/shopify-app-template-node#12]
When building the Docker image, I get this error:

`ERROR [11/14] RUN npm --prefix ./frontend run upload `

The command `upload` doesn't exist in `/web/frontend/package.json`. My guess is that the goal is to run `upload_src_maps`?

**Comment by SaeedYasin** [comment]
Yes, that is correct and thank you for pointing out. 

I added the fix, https://github.com/SaeedYasin/shopify-frontend-template-react/blob/b99201414e7cc637b58199ec027558234f3512e2/package.json#L9

**Comment by afunnydev** [comment]
Perfect, thanks a lot for the quick answer and for your work 👍
