### ISSUE TITLE
Using separate frontend other than React

### ISSUE THREAD

**Issue by basil2style** [SaeedYasin/shopify-app-template-node#5]
Is it possible to add a separate frontend framework (Vue, Svelte) other than React in to this project? I saw that` @shopify/app-bridge-react` is tightly coupled with React if I'm not wrong,

**Comment by SaeedYasin** [comment]
Yes, you are correct. Besides '@shopify/app-bridge' we also have '@shopify/polaris' etc which only works with react. From what I understand, Shopify code won't work without react. Unless these libraries are recreated to work with other frameworks, we are stuck with react.
