### ISSUE TITLE
JWT with Postman

### ISSUE THREAD

**Issue by petrakoww** [SaeedYasin/shopify-app-template-node#9]
Hello, I want to use Postman for requests to the back-end.  When I send a request, the response is some JWT and "signature verification failed". I don't have .env file. Where can I find the secret for the token?

**Comment by SaeedYasin** [comment]
Hi there,

Did you manage to find the answer? You might share it here as well, in case you have the answer.

**Comment by petrakoww** [comment]
Yup, this buddy's comment helped me.
#https://github.com/Shopify/shopify-api-js/issues/632#issuecomment-1412262707
